title: @haileybot/captcha-generator
description: Generate captcha images for use with bots on chat platforms
google_analytics: 
show_downloads: false
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
